apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  values:
    serviceAccount:
      create: true
      name: loki

    loki:
      schemaConfig:
        configs:
          - from: "2020-05-15"
            store: tsdb
            object_store: s3
            schema: v12
            index:
              prefix: loki_index_
              period: 24h

      storageConfig:
        tsdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/index_cache
          shared_store: s3
        aws:
          s3: s3://ap-southeast-7
          bucketnames: order-system-monitoring-loki

    ingester:
      persistence:
        enabled: true
        claims:
        - name: data
          size: 5Gi
          storageClass: gp2

    querier:
      persistence: { enabled: true, size: 3Gi, storageClass: gp2 }

    compactor:
      persistence:
        enabled: true
        claims:
        - name: data
          size: 3Gi
          storageClass: gp2

