apiVersion: v1
kind: Service
metadata:
  name: shop-service
  namespace: apps
  labels:
    app.kubernetes.io/name: shop-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: shop-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shop-service
  namespace: apps
  labels:
    app.kubernetes.io/name: shop-service
spec:
  serviceName: shop-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: shop-service
  template:
    metadata:
      namespace: apps
      labels:
        app.kubernetes.io/name: shop-service
        app.kubernetes.io/instance: shop-service
    spec:
      containers:
      - name: shop-service
        image: nvhuu991/order-system:shop-service
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: apps-env
