apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: apps
  labels:
    app.kubernetes.io/name: api-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      name: api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-gateway
  namespace: apps
  labels:
    app.kubernetes.io/name: api-gateway
spec:
  serviceName: api-gateway
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: api-gateway
  template:
    metadata:
      namespace: apps
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/instance: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: nvhuu991/order-system-api-gateway
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 100m
            memory: 512Mi
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: apps-env
