---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAXmchxf8Tmz/DcW7pXjj+yw3kkJlVa6IJQ16SIkDQDHH3HEpV4ZzA036uYvyhfh38a5+Jo72/Mf5S5DxU997GuLc7PcDy/3VGVWyGBzFr60UVtg0xMUDp7Q2reU0H84GVlSrGL2juJbUrQJVOKH2PKtvGfcxUU9TzfZRGWWVeD+Z20FBJrgkipdjF9Xn6SNp4OZS8GnJESGltWl/KWfMBHIVZlUzDpXrT2Hn93WRCJa/ZB1gs3XLAiHXGnvTRWHhtc1GnLMBayafsdhFWR5Va4dfZnfiQtrFkluEi8gtkh250W6w2eOgRVVyp9auSE5pOK4Ca0Zst7VRMbjaT0w9Y6CgfcCBa87uTNrkxkDHg2pf+EFVZnEBNEfxidYfkZdHlmPk2jAsmBhw3UMrjbzeA5QNUvlSXggAhkzF9ENky0xIfZjXURTj1a+wtCbGtGyRI3cdnnxM1fgxbUxo43FKcM9zlz7yHKl+S+OsrKJrGpy7OSzY4PnrlnjA9N7Pz3WEV0b3u0jD7JvbYGbko05QvclELsqpOSgWirz7cgD+TNMz1rVrLYAA/JKtJMlAceDtRdKwa/JSRUtrbhn2E+meS1D29PlQB0RXMsJ8AV5bzrlFicsNA9GpMvxRaf6WofYTc/5oEAZUv7E8i+Xu7grP8klWpTDvjTmxxXm6f3/6Dm7zDsSfSZdWhXKVzEz3aDg60lQKs9CA==
    admin-user: AgANsv3ri+6O8g1Fa3rM/QofkvxjCD6UYkLaKc8MOqF1z9jf7aJikT7pzuRvl8eLwuYPt4N1DyxIKGNvxs21N8BXgpwi/vknA/PLT67LWNzW9WN4JygTIsdJSUxwBiRj9oXVmiCsH7R4Bz79WfAUV6eyQxDjkTKhIX3lzd/r0pscA2kYbHpLejszYvz+XnR61YAupA3else7aJXsZil4m5GhlJHtAFd128CktEZn0VWWOIWFFuuqwS5kubkwV/02w9V6yZlqR5xDWVOWBfk0kCjFicTNpqJOK6bd3k3Hg3jYf6Zb42eYxalCwmaiwEAXKVYY1ISSTMVaBniZ7HHeWj6qKle2uIb+POtReobQ7Q9GMvoJJtcwn1GtlvE+n+7nx9pH1HGKWvZXQXmKgEV1YeqONWqd18FzSCBaB0hkSXj3PTsVVdwOuHah+9AjFvWt1V4+dHiev1+MOXUAcP7cAYOcONypMFVbyrmD8JLAMu49/5FK6QQXFteKERTRNNs1cL2E0SgIpwFJ471YBQdO82Xyv1JdovFW/STsi/XNUEQKbNiOcUKgDTvIGe4F+J+FakaHz8/rpdhHga7JZ7l5KfKhB0GIrWINgBE1og/IrZRluB0sYNWVO5wC2kdI7ZPDsP1LbOyn2nOWzEED9T7Y0usanjrpGErXFsaFot/gkFoglGPyU5n8gITG7fHaZjpUfOXMzfmVhQ==
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
