apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: infras
spec:
  values:
    serviceAccount:
      create: true
      name: tempo

    tempo:
      image:
        registry: docker.io
        repository: grafana/tempo
        tag: 2.9.0
      
    storage:
      trace:
        backend: s3
        s3:
          region: ap-southeast-7
          bucket: order-system-monitoring-tempo

    distributor:
      persistence: { enabled: true, size: 3Gi, storageClass: gp2 }

    ingester:
      persistence: { enabled: true, size: 5Gi, storageClass: gp2 }

    compactor:
      persistence: { enabled: true, size: 3Gi, storageClass: gp2 }
