apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  values:
    serviceAccount:
      create: true
      name: tempo

    storage:
      trace:
        backend: s3
        s3:
          region: ap-southeast-7
          bucket: order-system-monitoring-tempo
          endpoint: s3.ap-southeast-7.amazonaws.com

    ingester:
      persistence: { enabled: true, size: 5Gi, storageClass: gp2 }

