apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: monitoring
spec:
  values:

    grafana:
      persistence:
        enabled: true
        type: sts
        storageClassName: gp2
        accessModes: ["ReadWriteOnce"]
        size: 3Gi
        finalizers:
          - kubernetes.io/pvc-protection

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: gp2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
              selector: {}
          