apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shop-service
  namespace: apps
spec:
  replicas: 1
  template:
    spec:
      resources:
        requests: { cpu: 100m, memory: 384Mi }
        limits: { cpu: 100m, memory: 384Mi }
