apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: apps
  labels:
    app.kubernetes.io/name: inventory-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: inventory-service
  ports:
    - port: 8083
      targetPort: 8083
      name: api
    - port: 9093
      targetPort: 9093
      name: grpc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-service
  namespace: apps
  labels:
    app.kubernetes.io/name: inventory-service
spec:
  serviceName: inventory-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: inventory-service
  template:
    metadata:
      namespace: apps
      labels:
        app.kubernetes.io/name: inventory-service
        app.kubernetes.io/instance: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: nvhuu991/order-system-inventory-service
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 384Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
          - containerPort: 8083
          - containerPort: 9093
        envFrom:
          - configMapRef:
              name: apps-env
