apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: infras
spec:
  values:
    controller:
      resources:
        requests: { cpu: 100m, memory: 640Mi }
        limits: { cpu: 100m, memory: 640Mi }
