apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: apps
  labels:
    app.kubernetes.io/name: cart-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: cart-service
  ports:
    - port: 8081
      targetPort: 8081
      name: api
    - port: 9091
      targetPort: 9091
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-headless
  namespace: apps
  labels:
    app.kubernetes.io/name: cart-service
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: cart-service
  ports:
    - port: 8081
      targetPort: 8081
      name: api
    - port: 9091
      targetPort: 9091
      name: grpc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cart-service
  namespace: apps
  labels:
    app.kubernetes.io/name: cart-service
spec:
  serviceName: cart-service-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cart-service
  template:
    metadata:
      namespace: apps
      labels:
        app.kubernetes.io/name: cart-service
        app.kubernetes.io/instance: cart-service
    spec:
      containers:
      - name: cart-service
        image: nvhuu991/order-system:cart-service-v3.0.1
        resources:
          requests:
            cpu: 1
            memory: 384Mi
          limits:
            cpu: 1
            memory: 512Mi
        ports:
          - containerPort: 9091
          - containerPort: 8081
        envFrom:
          - configMapRef:
              name: apps-env
