apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: integration
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./integration/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system