apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: infras
spec:
  interval: 1h
  timeout: 10m
  releaseName: kafka
  targetNamespace: infras
  chart:
    spec:
      chart: kafka
      version: 32.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: infras

  values:
    image:
      registry: docker.io
      repository: bitnamilegacy/kafka
      tag: 4.0.0-debian-12-r10

    listeners:
      client:
        protocol: PLAINTEXT
      controller:
        protocol: PLAINTEXT
      interbroker:
        protocol: PLAINTEXT

    controller:
      # deploy as single process (broker + controller)
      controllerOnly: false
      replicaCount: 3
      persistence: { enabled: true, size: 3Gi, storageClass: standard }
      resources:
        requests: { cpu: 100m, memory: 640Mi }
        limits: { cpu: 100m, memory: 640Mi }