apiVersion: batch/v1
kind: Job
metadata:
  name: cart-update-load-test
  namespace: apps
  labels:
    app.kubernetes.io/name: cart-service
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "/scripts/cart-update-load-test.js"]
          resources:
            requests: { cpu: "200m", memory: "128Mi" }
            limits: { cpu: "200m", memory: "128Mi" }
          envFrom:
            - configMapRef:
                name: apps-env
          env:
            - name: TOTAL_VUS
              value: "10"
            - name: TOTAL_REQUESTS_PER_VU
              value: "100"
            - name: MAX_DURATION
              value: "60s"
            - name: "CART_SVC_INSTANCES"
              value: |- 
                cart-service-0.cart-service-headless.apps.svc.cluster.local,
                cart-service-1.cart-service-headless.apps.svc.cluster.local,
                cart-service-2.cart-service-headless.apps.svc.cluster.local,
                cart-service-3.cart-service-headless.apps.svc.cluster.local
          volumeMounts:
            - name: k6-script
              mountPath: /scripts
      volumes:
        - name: k6-script
          configMap:
            name: cart-update-load-test-script
            items:
              - key: cart-update-load-test.js
                path: cart-update-load-test.js
