apiVersion: batch/v1
kind: Job
metadata:
  name: cart-update-soak-test
  namespace: apps
  labels:
    app.kubernetes.io/name: cart-service
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "/scripts/cart-update-soak-test.js"]
          resources:
            requests: { cpu: "200m", memory: "128Mi" }
            limits: { cpu: "200m", memory: "128Mi" }
          envFrom:
            - configMapRef:
                name: apps-env
          env:
            - name: REQUESTS_PER_SECOND
              value: "100"
            - name: ERROR_RATE
              value: "0.2"
            - name: DURATION
              value: "10m"
          volumeMounts:
            - name: k6-script
              mountPath: /scripts
      volumes:
        - name: k6-script
          configMap:
            name: cart-update-load-test-script
            items:
              - key: cart-update-soak-test.js
                path: cart-update-soak-test.js
