apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 1h
  timeout: 10m
  releaseName: linkerd-crds
  targetNamespace: linkerd
  chart:
    spec:
      chart: linkerd-crds
      version: 2025.10.4
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
        namespace: linkerd
  values:
    installGatewayAPI: false