apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: infras
spec:
  values:
    controller:
      resources:
        requests: { cpu: 100m, memory: 256Mi }
        limits: { cpu: 100m, memory: 256Mi }
