apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: infras
spec:
  values:
    controller:
      resources:
        persistence: { enabled: true, size: 1Gi, storageClass: gp2 }
